# Use postgres/example user/password credentials
version: "3.9"

services:
  # api:
  #   build: .
  #   restart: always
  #   ports:
  #     - 30001:30001
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@db:5432/postgres
  #     REDIS_URL: redis://redis:6379/0

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    command: redis-server

volumes:
  pgdata:  
  redis:
  redis-config:
