# Use postgres/example user/password credentials
version: "3.9"

services:

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - authapi

  authapi:
    image: authapi
    restart: always
    deploy:
      replicas: 4
    # ports:
    #   - 3001:3001
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    command: redis-server

volumes:
  pgdata:  
  redis:
  redis-config:
