# Use postgres/example user/password credentials
version: "3.9"

services:

  watchtower:    
    image: containrrr/watchtower
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_TRACE: true
      WATCHTOWER_DEBUG: true
      WATCHTOWER_DISABLE_CONTAINERS: watchtower,nginx,db,adminer,redis
    command: --interval 30 authapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:   
    image: nginx:alpine
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - authapi

  authapi:    
    build: .
    image : petarnenov/authapi
    restart: always
    deploy:
      replicas: 2
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}

      - REDIS_URL=${REDIS_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REQ_PER_MINUTE=${REDIS_REQ_PER_MINUTE}
      - REDIS_ACCESS_TOKEN_EXPIRES_IN=${REDIS_ACCESS_TOKEN_EXPIRES_IN}
      - REDIS_REFRESH_TOKEN_EXPIRES_IN=${REDIS_REFRESH_TOKEN_EXPIRES_IN}

      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRES_IN=${JWT_ACCESS_TOKEN_EXPIRES_IN}
      - JWT_REFRESH_TOKEN_EXPIRES_IN=${JWT_REFRESH_TOKEN_EXPIRES_IN}

      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}

  db:    
    image: postgres
    restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  adminer:    
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    command: redis-server

volumes:
  pgdata:  
  redis:
  redis-config:
