export default {
  COMMON: {
    BAD_REQUEST: "BAD_REQUEST",
    NOT_FOUND: "NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  },
  AUTH: {
    LOGIN: "AUTH_LOGIN",
    SIGNUP: "AUTH_SIGNUP",
    LOGOUT: "AUTH_LOGOUT",
    REFRESH: "AUTH_REFRESH",
  },
  USERS: {
    GET_USER_BY_ID: "GET_USER_BY_ID",
    DELETE_USER: "DELETE_USER",
    GET_USERS: "GET_USERS",
    UPDATE_USER: "UPDATE_USER",
    HAS_BEEN_DELETED: "USER_HAS_BEEN_DELETED",
    ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    INCORRECT_CREDENTIALS: "USER_OR_PASSWORD_INCORRECT",
    INVALID_TOKEN: "USER_INVALID_TOKEN",
  },
  GREET: {
    HELLO: "HELLO",
  },
};
